server {
  listen 80;
  listen [::]:80;
  server_name test.43-160-242-46.sslip.io test-s3.43-160-242-46.sslip.io;

  access_log off;
  error_log /dev/null emerg;

  location ^~ /.well-known/acme-challenge/ {
    root /var/lib/letsencrypt;
    default_type text/plain;
    try_files $uri =404;
  }

  location / {
    return 503 'Test environment is not published.\n';
  }
}
