// Session noise predicates shared by import parsing and extract clustering.
// These strings are generated by coding-agent runtimes, not by the user task itself.

const PLATFORM_PROMPT_PREFIXES = [
  '<environment_context>',
  '# AGENTS.md instructions',
  '# Files mentioned by the user:',
  '<local-command-caveat>',
  'Generate a title and a git branch name for a coding agent from the user prompt',
  'You are editing a Markdown artifact for a local AI doc editor.',
];

// 这类注入是完整 XML 包裹块；Codex Desktop 可能把多个宿主块合并成一条 user 消息。
// 只在整条消息能被一个或多个已知块完整消费时过滤，避免误伤用户正文里的 XML 讨论。
const PLATFORM_PROMPT_WRAPPERS = ['recommended_plugins', 'environment_context'];

function isOnlyKnownPlatformWrappers(text: string): boolean {
  let remaining = stripRolePrefix(text.trim());
  let consumed = false;
  const tags = PLATFORM_PROMPT_WRAPPERS.join('|');
  const wrapper = new RegExp(`^<(${tags})(?:\\s[^>]*)?>[\\s\\S]*?<\\/\\1>\\s*`, 'i');

  while (remaining.length > 0) {
    const match = wrapper.exec(remaining);
    if (!match) return false;
    consumed = true;
    remaining = remaining.slice(match[0].length).trimStart();
  }
  return consumed;
}

export function firstNonEmptyLine(text: string | null | undefined): string {
  if (!text) return '';
  return (
    text
      .replace(/\r\n/g, '\n')
      .split('\n')
      .map((line) => line.trim())
      .find((line) => line.length > 0) ?? ''
  );
}

export function stripRolePrefix(line: string): string {
  return line.replace(/^(user|assistant|system|tool):\s*/i, '').trim();
}

export function isPlatformPromptText(text: string | null | undefined): boolean {
  if (!text) return false;
  if (isOnlyKnownPlatformWrappers(text)) return true;
  const first = stripRolePrefix(firstNonEmptyLine(text));
  if (!first) return false;
  const lower = first.toLowerCase();
  return PLATFORM_PROMPT_PREFIXES.some((prefix) => lower.startsWith(prefix.toLowerCase()));
}

export function isBlockedCapabilityLabel(text: string | null | undefined): boolean {
  const first = firstNonEmptyLine(text);
  if (!first) return true;
  return isPlatformPromptText(first);
}
