apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      annotations:
        combo.build/release-contract: v1
    spec:
      containers:
        - name: migrate
          env:
            - name: PGHOST
              value: combo-postgres-host
          envFrom:
            - configMapRef:
                name: combo-release
