apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: combo-foundation
resources:
  - ../../postgres.yaml
  - ../../redis-queue.yaml
  - ../../redis-hot.yaml
  - ../../minio.yaml
  - ../../job-minio-init.yaml
patches:
  - target:
      kind: Service
      name: minio
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      combo.build/foundation-set: shared
